version: '3.3'
services:

  db:
    image: postgres:15-alpine
    volumes:
      - data_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    container_name: foodgram_data

  backend:
    image: ellrik/foodgram_backend
    restart: always
    volumes:
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    container_name: foodgram_backend

  frontend:
    image: ellrik/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
    container_name: foodgram_frontend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - media_value:/var/html/media/
      - ../static/:/var/html/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - backend
      - frontend
    container_name: foodgram_nginx

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  data_db:
  media_value:
