version: '3.3'
services:

  db:
    image: postgres:15-alpine
    volumes:
      - data_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    container_name: foodgram_data

  backend:
    image: ellrik/foodgram_backend
    build: ../backend/api_foodgram
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    container_name: foodgram_backend

  frontend:
    image: ellrik/foodgram_frontend
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
    container_name: foodgram_frontend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ../frontend/build/static:/var/html/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    container_name: foodgram_nginx

volumes:
  data_db:
  static_value:
  media_value:
